### ISSUE TITLE
Teams Integration - Epic

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#507]
This Epic issue is to capture smaller stories and related sub tasks. The [Teams](https://github.com/developmentseed/osm-teams) integration into Scoreboard requires the following steps:
- [x]  Sync new Teams API with Scoreboard #481 
- [x] Expose Connect Teams Button #501
- [x] Pull all Public Teams into Scoreboard #502 
- [x] Pull user's teams into Scoreboard (finish Teams Index page) #503 
- [x] Create Team #504 
- [x] Edit Team from Scoreboard #505 
- [x] Team Moderators Can Assign Campaigns #506 
- [x] Single Team Page (Team Stats) #198
- [x] -> Team Stats empty state #542 
- [x] -> ~Team Stats Join Button~ Striking this from the current milestone. Tracked in #539
- [x] -> Team Stats page Edit Team link, conditional Team campaigns section #545 
- [x] -> Create Team button #563 

@kamicut the above stories/issues are all assigned to you by default - please break up into smaller sub-tasks, re-assign and distribute as you see fit

/cc @geohacker @guidorice

**Comment by guidorice** [comment]
Converted the numbered list to checklist.

**Comment by kamicut** [comment]
We have roughly one sprint until April 15, our deadline for wrapping up NOME. Here's the current state of each item:

- Sync new Teams API with Scoreboard #481: This is done, but needs to be re-visited with the new organizations API to make sure Scoreboard communicates with organizations
- Pull all Public Teams into Scoreboard #502 & Pull user's teams into Scoreboard #503: Done on the osm-teams side. Scoreboard side is started but we need to add the extra route and style the tables. 
- Create Team from Scoreboard #504: 80% done, just need to make sure the OSM Teams permissions work as planned. I am taking on this task 
- Edit Team from Scoreboard #505: 25% done. I am taking on this task
- Team Moderators Can Assign Campaigns #506. 0% done. I am taking on this task as part of the edit team from Scoreboard
- Single Team Page #198: @guidorice to estimate how much is needed here. 

With that said, these is only the functional aspects of the delivery which I estimate we can deliver by April 15, or April 21 at the latest cc @geohacker. This doesn't include deployment and documentation.

**Comment by guidorice** [comment]
I closed #198 and split the remaining work on Team Stats page into 3 issues. (checklist updated above) These issues get into adding new routes, osm-teams permissions, and conditional rendering logic, so I am estimating 3 days (1 day per issue).

/cc @kamicut @geohacker @LanesGood

**Comment by guidorice** [comment]
@kamicut @LanesGood can you review this ticket and then move into Ready to Deploy if it looks good?

**Comment by LanesGood** [comment]
All complete - moving to RTD
