### ISSUE TITLE
Tasks in Scoreboard

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#67]
# Tasks in Scoreboard

## Task Attributes
For each page of tasks pulled from the API, the following will be displayed:

• Name of task
• Percent completed
• Percent validated
• Priority

The following will also be used and/or provided:

• GeoJSON
• Link to task

Note that for each of the first four attributes, we will need to make a separate API call since the only attributes provided in the basic search is the Project ID and priority.

For now, we will follow the task manager's example of:

• Showing the most urgent projects by default
• Displaying 14 results per page
• Allowing users to search projects by name, priority, mapper level

## Open Questions
• What other data do we need to pull for the project page (as opposed to the card)?

**Comment by alyssadelaine** [comment]
To begin restructuring the code, I'm going to first pull the following for a subset of tasks from TM 3 and provide them via the api/campaigns api route
- tm_id
- name
- description
- geometry
- campaign_hashtag
- done
- validated

**Comment by alyssadelaine** [comment]
### Update

#### Done
Reconciled the new structure of TM 3 tasks with the database schema
#### To Do
[Restructure](https://github.com/developmentseed/scoreboard/pull/96#discussion_r237527442) the code which iterates through the pages of tasks and imports each into the database
The other steps, which can be done out of order, are to 
1) Have multiple tabs on the campaigns page for each type of supported tasking manager 
    * Will require a change to the database to add a "Version" column
2) Display results straight from the API as opposed to storing tasks and then refreshing the database
    * Will require caching

cc @kamicut

**Comment by kamicut** [comment]
I'm adding a backlog here for this ticket

- [ ] Create Admin page to tasking managers
- [ ] Create database table to add tasking manager to db
- [ ] Create routes to add / edit / delete tasking manager from db
- [ ] Create form to add / edit / delete tasking manager from db
- [ ] Modify clocks process to read from db instead of hardcode

**Comment by kamicut** [comment]
After a discussing with @alyssadelaine, I think we can skip adding TM_HASHTAG to the database and make `extractCampaignHashtag` a bit smarter about how to get the main hashtag from a campaign. 

The wip in project branch for this ticket is https://github.com/developmentseed/scoreboard/tree/feature/admin-tasks
